version: '3.7'

services:
  chinook:
    build:
      args: 
        - UID=$UID
        - GID=$GID
      context: ./
      dockerfile: ./chinook/Dockerfile
      target: development
    environment:
      - UID=$UID
      - GID=$GID
    tty: true # docker run -t
    stdin_open: true # docker run -i
    volumes:
      - ./chinook/modules/:/chinook/modules/
      - ./chinook/notebooks/:/chinook/notebooks/
      - ./chinook/output/:/chinook/output/
    ports:
      - $JUPYTER_PORT_APP:8888
    env_file:
      - ./.env

  chinook_db:
    build:
      context: ./
      dockerfile: ./chinook_db/Dockerfile
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: